### ISSUE TITLE
CT: Should not be calling setText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/xray-diffraction#3]
Probably due to https://github.com/phetsims/scenery/issues/1472.

```
xray-diffraction : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/xray-diffraction/xray-diffraction_en.html?continuousTest=%7B%22test%22%3A%5B%22xray-diffraction%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667521640987%22%2C%22timestamp%22%3A1667524264391%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Should not be calling setText
Error: Assertion failed: Should not be calling setText
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/assert/js/assert.js:28:13)
at assert (RichText.ts:946:14)
at (XrayDiffractionScreenView.js:234:8)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (DerivedProperty.ts:157:12)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
id: Bayes Puppeteer
Snapshot from 11/3/2022, 6:27:20 PM
```

**Comment by marlitas** [comment]
Fixed! Did some more fuzzing, and it doesn't look like there's anymore instances of this. Closing.
